from os import PathLike
from typing import ClassVar, Literal

class ValidationStatus:
    VALID: ClassVar[ValidationStatus]
    INVALID: ClassVar[ValidationStatus]
    UNSUPPORTED: ClassVar[ValidationStatus]

    @property
    def value(self) -> Literal["valid", "invalid", "unsupported"]: ...
    def as_bool(self) -> bool | None: ...

class CheckResult:
    @property
    def status(self) -> ValidationStatus: ...
    @property
    def code(self) -> str | None: ...
    @property
    def reason(self) -> str | None: ...
    @property
    def is_valid(self) -> bool: ...

class ValidationResult:
    @property
    def signature(self) -> CheckResult: ...
    @property
    def structure(self) -> CheckResult | None: ...
    @property
    def status(self) -> ValidationStatus: ...

def inspect_file(
    path: str | PathLike[str], *, signature_only: bool = False
) -> ValidationResult: ...
def check_file(
    path: str | PathLike[str], *, signature_only: bool = False
) -> tuple[bool | None, bool | None]: ...
def signature_check(
    path: str | PathLike[str], extension: str
) -> bool | None: ...
def structure_check(
    path: str | PathLike[str], extension: str
) -> bool | None: ...
def main() -> int: ...
