[package]
name = "masquerade"
description = "Dependency-free media file validation"
readme = "README.md"
keywords = ["file-type", "media", "security", "validation"]
categories = ["multimedia", "parser-implementations"]
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true
